#!/usr/bin/python

from Gluster.GFrontEnd import dialog
import os, sys

dlg = dialog.Dialog ()

def main ():
    (ret, sel) = dlg.menu ('Select',
                           choices=[('halt', 'Shutdown the system'),
                                    ('reboot', 'Reboot the system')],
                           title='[ Shutdown ]')
    if ret != 0:
        return

    if sel == 'halt':
        os.system ('shutdown -h now')
        while True:
            os.system ('sleep 108')
    if sel == 'reboot':
        os.system ('reboot')
        while True:
            os.system ('sleep 108')
    return

main ()
