#!/bin/sh
# Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#  

_init ()
{
    pkg_name="hpc-base"
    os_base="/tmp/ginstaller";
    prefix="/opt/gluster";
    return 0
}

main ()
{
    local my_dir="$(dirname $0)";

    # collect hardware profiles of all machines
    ghwdump

    for key in $(gmount -o); do
	
	# Customize the network of the network
	customize-net $os_base/$key
	STDIN=/dev/null gcsh customize-net $os_base/$key
	
        # overriding stuff on master node
	tar -C ${my_dir}/destdir_$(uname -m) -c . | tar -C $os_base/$key -x
	# overriding stuff on slave nodes
	tar -C ${my_dir}/destdir_$(uname -m) -c . | gcsh tar -C $os_base/$key -x

	# keep the cluster state in OS mode
	mkdir -p $os_base/$key/$prefix/state
	cp -af /var/gluster/{macs.txt,clientinfo,hw-profiles} $os_base/$key/$prefix/state
	cp -f /tmp/ghosts/known_hosts $os_base/$key/$prefix/etc/nodes

	# Send the cluster state to client nodes
	STDIN=/dev/null gcsh mkdir -p $os_base/$key/$prefix/state
	tar -C /var/gluster -c ./{macs.txt,clientinfo,hw-profiles} | gcsh tar -C $os_base/$key/$prefix/state -x
	STDIN=/tmp/ghosts/known_hosts | gcsh dd of=$os_base/$key/$prefix/etc/nodes

	# setup on master node
	$os_base/$key/$prefix/setup/$pkg_name-master $os_base/$key
	# setup on client node
	STDIN=/dev/null gcsh $os_base/$key/$prefix/setup/$pkg_name-slave $os_base/$key
    done
}

_init "$@" && main "$@";
