#!/bin/sh
# Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#  

_init ()
{
    pkg_name="genders"
    os_base="/tmp/ginstaller";
    prefix="/opt/gluster";
    return 0
}

main ()
{
    local my_dir="$(dirname $0)";
    for key in $(gmount -o); do
	for tgz in ${my_dir}/*.tgz; do
	    # install on master node
	    cat $tgz | tar -C /tmp/ginstaller/$key -xz;
	    # install on ALL slave nodes
	    cat $tgz | gcsh tar -C /tmp/ginstaller/$key -xz;
	done
	# overriding stuff on master node
	tar -C ${my_dir}/destdir -c . | tar -C /tmp/ginstaller/$key -x
	# overriding stuff on slave nodes
	tar -C ${my_dir}/destdir -c . | gcsh tar -C /tmp/ginstaller/$key -x

	# setup on master node
	$os_base/$key/$prefix/setup/$pkg_name-master $os_base/$key
	STDIN=/dev/null gcsh $os_base/$key/$prefix/setup/$pkg_name-slave $os_base/$key
	
    done
}

_init "$@" && main "$@";


