#!/bin/sh
# Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#  

os_base=$1
conf=$os_base/opt/gluster/etc/slurm.conf

cat $(dirname $0)/slurm.conf.in > $conf
cd $os_base/opt/gluster/state/hw-profiles
all_nodes=""
for node in *; do
   no_procs=$(grep cpu $node | wc -l)
   echo "NodeName=$node Procs=$no_procs State=UNKNOWN" >> $conf
   if [ -z "$all_nodes" ]; then
       all_nodes=$node;
   else
       all_nodes="$all_nodes,$node";
   fi
done

echo "PartitionName=allofthem Nodes=$all_nodes Default=YES MaxTime=-1 State=UP" >> $conf

ln -sf /opt/gluster/etc/slurm.conf $os_base/etc/slurm.conf