#!/bin/sh


echo " * Importing SSH host key pairs"
atftp --get --remote-file etc-ssh.tar --local-file /tmp/etc-ssh.tar master-node
mkdir -p /etc/ssh
tar -C /etc/ssh -xf /tmp/etc-ssh.tar

echo " * Importing SSH auth keys and pre-initialized known_hosts"
atftp --get --remote-file dot-ssh.tar --local-file /tmp/dot-ssh.tar master-node
mkdir -p /.ssh
tar -C /.ssh -xf /tmp/dot-ssh.tar 

echo " * Starting SSH daemon"
/usr/sbin/sshd

echo " * Importing HOSTS file"
atftp --get --remote-file hosts --local-file /tmp/hosts master-node
cat /tmp/hosts > /etc/hosts

echo " * Starting GPing daemon"
echo up > /tmp/.status.in
gpingd /tmp/.status.in
echo up > /tmp/.gping.in
gpingd -p 1332 /tmp/.gping.in

gcshd

exec /bin/bash --login
