#!/bin/sh

_init ()
{
   EXTENSIONS="client-reg mac-collector bootp-manager bootdisk-manager client-boot gutils fs-utils auth net-utils"
}

main ()
{
    local my_dir="$(dirname $0)";
    cp -alf "${my_dir}"/destdir/* /;

    if [ "$1" = "--client" ]; then
	return 0
    fi

    for ext in $EXTENSIONS
    do
      gex --install /stage3/$ext.gex;
    done

    exec GlusterEP "$@";
}

_init "$@" && main "$@";
