#!/usr/bin/python

import os, sys, string, ConfigParser

reg = ConfigParser.ConfigParser ()
clientinfo = '/var/gluster/clientinfo'
reg.read (clientinfo)

def get_hostname (s=''):
    return reg.get ('global', 'hostname') + s

def get_totalnodes ():
    return int (reg.get ('global', 'totalnodes'))

def main ():
    os.system ('mkdir -p /tmp/ghosts')
    all_hosts = file ('/tmp/ghosts/all_hosts', 'w')
    known_hosts = file ('/tmp/ghosts/known_hosts', 'w')

    for i in range (get_totalnodes ()):
        all_hosts.write ("%s%d\n" % (get_hostname (), i+1))
    all_hosts.close ()
    known_macs = file ("/var/gluster/macs.txt").readlines ()
    node_id = map (lambda x: int (x.split ()[0]), known_macs)

    nodes = map (lambda x: "%s%d" % (get_hostname (), int (x)), node_id)

    for node in nodes:
        known_hosts.write (node + "\n")
    known_hosts.close ()

    os.system ("gping -i /tmp/ghosts/known_hosts | cut -f1 -d: > /tmp/ghosts/up_hosts")
    return

main ()
