#!/usr/bin/python
##
## Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
##  
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##  
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##  
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##  
##

import os, sys

def main ():
    base_dir = '/var/gluster/hw-profiles'
    os.system ("mkdir -p %s" % base_dir)
    os.system ("STDIN=/dev/null gcsh 'ghwprobe > /tmp/.status.in' >/dev/null 2>&1")
    fd = os.popen ("gping -i /tmp/ghosts/known_ip")
    nodes_lines = fd.readlines ()
    fd.close ()
    masternode_line = os.popen ("ghwprobe").readline ()
    for node_line in nodes_lines + ['master-node: %s' % masternode_line]:
        node_line = node_line.strip ()
        node_name = node_line.split (':', 1)[0].strip ()
        node_status = node_line.split (':', 1)[1].strip ()
        details = node_status.split ()
        out_fd = file ('%s/%s' % (base_dir, node_name), "w")
        for detail in details:
            (key, vals) = detail.split ('=')
            for val in vals.split (','):
                out_fd.write ('%s=%s\n' % (key, val))
        out_fd.close ()
    return

main ()

