#!/usr/bin/python

import sys, os, string

def get_cpu_info ():
    info = os.popen ("cat /proc/cpuinfo | grep '^cpu MHz' | cut -d: -f2")
    lines = info.readlines ()
    info.close ()
    single_line = string.join (map (string.strip, lines), ",")
    return ("cpu=%s" % single_line)    

def get_memory_info ():
    info = os.popen ("cat /proc/meminfo | grep -E 'MemTotal|MemFree' | awk '{print $2}'")
    lines = info.readlines ()
    info.close ()
    single_line = string.join (map (string.strip, lines), ":")
    return ("mem=%s" % single_line)

def get_disk_info ():
    info = os.popen ("cat /proc/partitions| tail -n +3 | awk '{print $2\":\"$4\":\"$3}' | grep ^0: | cut -d: -f2,3")
    lines = info.readlines ()
    info.close ()
    single_line = string.join (map (string.strip, lines), ",")
    return ("disk=%s" % single_line)

def main ():
    info_file = sys.stdout
    info_file.write ("%s\n" % string.join ([get_cpu_info (),
                                          get_memory_info (),
                                          get_disk_info ()], " "))
    info_file.close ()
    return

main ()
