#!/usr/bin/python
##
## Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
##  
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##  
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##  
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##  
##

from Gluster.gpartdump import *
import sys

def main ():
    key = sys.argv[1]
    old_part = sys.argv[2]
    (old_disc, p) = get_disk_part (old_part)
    mapfd = file ('%s/boot/grub/device.map' % key)
    all_maps = map (string.strip, mapfd.readlines ())
    grub_disc = None
    for a_map in all_maps:
        pieces = a_map.split ()
        if pieces[0][0] == '#':
            continue
        if pieces[1] == old_disc:
            grub_disc = pieces[0].strip ('()')
            break
    if not grub_disc:
        print old_part
    else:
        if p:
            print '(%s,%d)' % (grub_disc, p - 1)
        else:
            print '(%s)' % grub_disc
                                                                                    
main ()
