#!/bin/sh
# Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#  

[ -f /tmp/ghosts/known_ip ] || ghosts --update-known-hosts 2>/dev/null
up_hosts=$(gping -i /tmp/ghosts/known_ip -p 1332 2>/dev/null| grep slave | wc -l)

[ "$up_hosts" = 0 ] && {
    echo "$0: 0 hosts alive, exiting"
    exit 1;
}
#echo -n "Commanding $up_hosts hosts $@ ... "
(echo "$@" && cat ${STDIN:-/dev/stdin}) | udp-sender --nokbd --portbase 10000 --min-clients $up_hosts >/dev/null 2>&1
#echo "done."
#echo -n "Waiting for completion ... "
udp-sender --nokbd --portbase 10002 --min-clients $up_hosts --file /dev/null >/dev/null 2>&1
#echo "done."
exit 0
