#!/bin/sh

export PS1='[\w]\$ '
export LD_LIBRARY_PATH=/lib:/lib64:/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/bin
#export PYTHONPATH=/usr/share/gluster

cd /

eval exec "$4"
