#!/bin/sh

os_base=$1

ln -fs /opt/gluster/etc/gmond.conf $os_base/etc/gmond.conf

## if Redhat/Fedora flavor
if [ -e "$os_base/etc/redhat-release" -o -e "$os_base/etc/fedora-release" ]; then 
    mv -f $os_base/etc/init.d/gmond.init.d.redhat $os_base/etc/init.d/gmond
    rm -f $os_base/etc/init.d/gmond.init.d.*
fi

## if SuSE flavor
if [ -e "$os_base/etc/SuSE-release" ]; then 
    mv -f $os_base/etc/init.d/gmond.init.d.suse $os_base/etc/init.d/gmond
    rm -f $os_base/etc/init.d/gmond.init.d.*
fi

chroot $os_base chkconfig --add gmond
