#!/usr/bin/python
##
## Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
##  
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##  
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##  
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
##  
##

from Gluster.GFrontEnd import dialog;
from Gluster import GArgs;

import kernel_image;
import pxe_image;
import mode;

boot_plug_func_map = {
    'kernel-image' : [kernel_image.plugme],
    'pxe-image' : [pxe_image.plugme]
};

dlg = dialog.Dialog ()

def boot_plugin (name):
    boot_plug_func_map[name][0] ();
    return;
    
_Reg = {
  'bootplug' : [ ['--bootplug'] ,
                  'string',
                  'ask',
                  'Which plugin for bootman extension'
               ]
};

GArgs._G.AddRawOptConf (_Reg);
GArgs._G.Process ();

plug = GArgs._G.GetValue ('bootplug');
if (plug == 'ask'):
    while (1):
        (ret, choice) = dlg.menu ("Choose a BootMan plugin", 
                                  choices=[('kernel-image', 
                                            'Boot disk with kernel/initrd'),
                                           ('pxe-image',
                                            'Boot disk for PXE/Network boot')])

        if ret != 0:
            break

        boot_plugin (choice);

else:
    boot_plugin (plug);
