#! /bin/sh
# Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#  

_init ()
{
    iface_info="/var/gluster/iface-info";
    hosts_file="/etc/hosts";
    return 0;
}

main ()
{
    local os_base="$1";
    my_hostname="$(hostname | cut -f1 -d'.')";
    
    my_details=($(grep "^$my_hostname\>" $iface_info));
    ## hostname ip ifacehost+domain ifacehost netmask iface <comments
    my_ip=${my_details[1]};
    my_mask=${my_details[4]};
    my_iface=${my_details[5]};
    
    ## This works ONLY for redhat flavors
    cat > $os_base/etc/sysconfig/network-scripts/ifcfg-$my_iface <<_EOF_
DEVICE=$my_iface
ONBOOT=yes
BOOTPROTO=static
IPADDR=$my_ip
NETMASK=$my_mask
_EOF_
    cp -f $os_base/etc/sysconfig/network-scripts/ifcfg-$my_iface $os_base/etc/sysconfig/networking/profiles/default/ifcfg-$my_iface
    cp -f $os_base/etc/sysconfig/network-scripts/ifcfg-$my_iface $os_base/etc/sysconfig/networking/devices/ifcfg-$my_iface
    ## Update the hosts file
    sed -e '/# Added by iface-cfg\/Gluster$/d' -i $os_base/$hosts_file
    grep -v '^master-node\>' $iface_info | cut -f2-4,7 >> $os_base/$hosts_file;
}

_init "$@" && main "$@";


