#! /bin/sh
# Copyright (C) 2006 Z RESEARCH Inc. <http://www.zresearch.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#  

_init ()
{
    iface_info="/var/gluster/iface-info";
    hosts_file="/etc/hosts";
    return 0;
}

main ()
{
    local os_base="$1";
    local my_dir="$(dirname $0)";
    my_hostname="$(hostname | cut -f1 -d'.')";

    my_details=($(grep "^$my_hostname\>" $iface_info));
    ## hostname ip ifacehost+domain ifacehost netmask iface <comments
    my_ip=${my_details[1]};
    my_mask=${my_details[4]};
    my_iface=${my_details[5]};

    ifconfig $my_iface $my_ip netmask $my_mask;
    customize-net $os_base;

    ## Update the hosts file
    sed -e '/# Added by iface-cfg\/Gluster$/d' -i $os_base/$hosts_file
    cut -f2-4,7 $iface_info >> $os_base/$hosts_file;
}

_init "$@" && main "$@";


